### PR TITLE
User story 4 set username

### PR DESCRIPTION
**Pull request by nickcbrierley**
I moved the logic from BlocChatCookies into the home controller and set it to hide the rest of the app until a username is entered.

### CODE REVIEW

**Comment by jklegseth** [comment]
I see the username input field even when I have a set user name:

**Review by jklegseth — CHANGES_REQUESTED** [review]
See my comment about username input being in view even though I have a cookie.

**Comment by nickcbrierley** [comment]
I intentionally kept the username field there to allow the user to change their username if they wished to, but I can change it to disappear.

**Comment by jklegseth** [comment]
Ok, that's your call. I question the user experience of that but it's your app.

**Review by jklegseth — APPROVED** [review]

**Pull request merged**
